Repository Olympic-code/MedCare, pull requests merged in 2022-11, with the labels that each got.

#18 [OLPO-49]: Adjusting project packages
  MedCare.Commons/Entities/EnumUsefulStrings.cs
  MedCare.Commons/entities/AbstractPatient.cs
  MedCare.Commons/entities/AbstractPerson.cs
  MedCare.Commons/entities/AbstractProfessional.cs
  MedCare.Commons/entities/AbstractUser.cs
  MedCare.Commons/entities/EnumPriority.cs
  MedCare.Commons/entities/EnumProcedureType.cs
  MedCare.Commons/entities/EnumUserType.cs
  MedCare.Commons/entities/MedicalProcedures.cs
  MedCare.Commons/entities/Messages.cs
  MedCare.Commons/entities/Patient.cs
  MedCare.Commons/entities/Professional.cs
  MedCare.DB/Databases/PatientDatabase.cs
  MedCare.DB/Databases/ProfessionalDatabase.cs
  MedCare.DB/DatabasesConfiguration.cs
  MedCare.DB/Services/IPatientRepository.cs
  MedCare.DB/Services/IProfessionalRepository.cs
  MedCare.DB/Services/PatientRepository.cs
  MedCare.DB/Services/ProfessionalRepository.cs
  MedCare.Patient/App.xaml.cs
  MedCare.Patient/MainWindow.xaml.cs
  MedCare.Patient/Properties/AssemblyInfo.cs
  MedCare.Professional/App.xaml.cs
  MedCare.Professional/MainWindow.xaml.cs
  MedCare.Professional/Properties/AssemblyInfo.cs
  MedCare.UnitTests/Services/AuthenticationServiceTest.cs
  MedCare/App.xaml
  MedCare/App.xaml.cs
  MedCare/CustomControls/BindablePasswordBox.xaml.cs
  MedCare/Exceptions/IncorrectPasswordException.cs
  MedCare/Exceptions/NotFoundUserException.cs
  MedCare/MainWindow.xaml
  MedCare/MedCare.csproj
  MedCare/Properties/AssemblyInfo.cs
  MedCare/Services/AuthenticationService/AuthenticationService.cs
  MedCare/Services/AuthenticationService/IAuthenticationService.cs
  MedCare/ViewModels/ViewModelBase.cs
  MedCare/ViewModels/ViewModelCommand.cs
  MedCare/ViewModels/ViewModelLogin.cs
  MedCare/Views/LoginView.xaml
  MedCare/Views/LoginView.xaml.cs
Labels: refact

#19 [OLPO-49]: Adding RegisterView.
  MedCare/MedCare.csproj
  MedCare/Views/RegisterView.xaml
  MedCare/Views/RegisterView.xaml.cs
Labels: enhancement

#20 [OLPO-47]: Refact login authentication code and create register authe…
  MedCare.UnitTests/Services/LoginAuthenticationServiceTest.cs
  MedCare.UnitTests/Services/RegisterAuthenticationServiceTest.cs
  MedCare/Exceptions/PasswordsAreNotEqualsException.cs
  MedCare/Exceptions/UserAlreadyExistsException.cs
  MedCare/MedCare.csproj
  MedCare/Services/AuthenticationService/AuthenticationService.cs
  MedCare/Services/AuthenticationService/IAuthenticationService.cs
Labels: enhancement

#21 [OLPO -51]: Applying Abstract Factory Pattern in Databases.
  MedCare.DB/Databases/AbstractPatientDatabase.cs
  MedCare.DB/Databases/AbstractProfessionalDatabase.cs
  MedCare.DB/Databases/PatientDatabase.cs
  MedCare.DB/Databases/PatientDatabaseTest.cs
  MedCare.DB/Databases/ProfessionalDatabase.cs
  MedCare.DB/Databases/ProfessionalDatabaseTest.cs
  MedCare.DB/DatabasesConfiguration.cs
  MedCare.DB/Factories/AbstractDatabaseFactory.cs
  MedCare.DB/Factories/EnumDatabaseTypes.cs
  MedCare.DB/Factories/PatientDatabaseFactory.cs
  MedCare.DB/Factories/ProfessionalDatabaseFactory.cs
  MedCare.DB/Services/PatientRepository.cs
  MedCare.DB/Services/ProfessionalRepository.cs
Labels: enhancement

#26 [OLOPO-55]: Created login view.
  MedCare.Application/App.xaml
  MedCare.Application/App.xaml.cs
  MedCare.Application/Assets/Images/equipe-medica.png
  MedCare.Application/Converters/MessageErrorVisibilityConverter.cs
  MedCare.Application/MedCare.Application.csproj
  MedCare.Application/Strings/pt-br/Resources.resw
  MedCare.Application/Styles/RegistrationStyles.xaml
  MedCare.Application/Themes/ColorsKey.xaml
  MedCare.Application/ViewModels/LoginViewModel.cs
  MedCare.Application/ViewModels/ViewModelLogin.cs
  MedCare.Application/Views/LoginView.xaml
  MedCare.Application/Views/LoginView.xaml.cs
  MedCare.Application/Views/RegistrationView.xaml
Labels: enhancement, refact
